config/routes.rb
Rails.application.routes.draw do
  resources :emps
  get 'home/index'

  get 'home/welcome'

  get 'home/about'

  get 'home/contact'

  get 'home/list'

  get 'home/edit'

  get 'home/delete'

end

app/models/emp.rb
class Emp < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: [:show, :edit, :update, :destroy]

  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1
  # PATCH/PUT /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: 'Emp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_params
      params.require(:emp).permit(:name, :bio, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/emps/_form.html.erb
<%= form_for(@emp) do |f| %>
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing Emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.bio %></td>
        <td><%= emp.birthday %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1>New Emp</h1>

<%= render 'form' %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @emp.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @emp.birthday %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>
11222

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>
  Say <a href="say/goodbye">Goodbye</a>!
</p>

app/views/home/list.html.erb
<h1>Home#index</h1>
<table>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.created_at %></td>
          <td><%= article.created_at %></td>
          <td><%= article.created_at %></td>
          <td><%= link_to 'Show', home_list_path(article) %></td>
          <td><%= link_to 'Edit', home_edit_path(article) %></td>
          <td><%= link_to 'Destroy', home_delete_path(article), :confirm => 'Are you sure?', :method => :delete %></td>
          <td><%= link_to "Issues", {:controller => "home", :action => "index"}, {:title => "Issues"} %></td>
        </tr>
    <% end %>
</table>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>